In [1]:
from llms.model_calls import GroqChatModel

In [2]:
groqllm = GroqChatModel(model_name="openai/gpt-oss-20b", temperature=0).client

[2026-06-12 12:44:18.260] [INFO] [ChatLLM_calls_log] - LLM initialized: openai/gpt-oss-20b, temperature: 0

In [3]:
groqllm.model_name

'openai/gpt-oss-20b'

In [4]:
from ragas.llms import llm_factory

[2026-06-12 12:44:26.949] [INFO] [numexpr.utils] - NumExpr defaulting to 4 threads.

In [5]:
llm_factory(model=groqllm.model_name, client=groqllm.client)

g:\ai_Data_Science\env\Lib\site-packages\ragas\llms\base.py:556: UserWarning: Client should be an instance of openai.OpenAI or openai.AsyncOpenAI. Unexpected behavior may occur with other client types.
  return instructor.from_openai(client, mode=instructor.Mode.JSON)

InstructorLLM(provider='openai', model='openai/gpt-oss-20b', client=<NoneType:sync>, temperature=0.01, max_tokens=1024, top_p=0.1)

In [1]:
import pandas as pd
df = pd.read_csv("eval_results\custom_scores_06172026__204318.csv")
df.head()

,question,response,ground_truth,faithfulness,context_recall,reasoning
0,"Who were the eight authors of ""Attention Is Al...",The names of the eight researchers who co-auth...,"Ashish Vaswani, Noam Shazeer, Niki Parmar, Jak...",1.0,1.0,The System Response is completely grounded in ...
1,What was the initial scaling factor for the ke...,The initial value of the scaling factor d_k fo...,64,1.0,1.0,The System Response is completely grounded in ...
2,Which dataset was used to train the English-to...,The English-to-German translation model was tr...,the 2014 WMT English-German dataset consisting...,1.0,1.0,The System Response is completely grounded in ...
3,How many NVIDIA P100 GPUs were used to train t...,The total number of NVIDIA P100 GPUs utilized ...,8 NVIDIA P100 GPUs,1.0,1.0,The System Response is completely grounded in ...
4,What is the formula for positional encoding fo...,The mathematical formula used for calculating ...,"PE(pos,2i)=sin(pos/10000^{2i/d_model})",0.9,1.0,The System Response is mostly grounded in the ...

In [4]:
df[df.columns[-3:]]

,faithfulness,context_recall,reasoning
0,1.0,1.0,The System Response is completely grounded in ...
1,1.0,1.0,The System Response is completely grounded in ...
2,1.0,1.0,The System Response is completely grounded in ...
3,1.0,1.0,The System Response is completely grounded in ...
4,0.9,1.0,The System Response is mostly grounded in the ...
5,0.9,1.0,The System Response is mostly grounded in the ...